[package]
name = "day_09"
version = "0.1.0"
authors = ["Maximilian Stock <me@maximumstock.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intcode = { path = "../intcode" }
